### ISSUE TITLE
crash when the account is not yet selected

### ISSUE THREAD

**Issue by giuliohome** [giuliohome/TweetSearch#2]
Saving to GDrive, maybe too fast) 

Stack

``` java
java.lang.NullPointerException
    at org.new_year.DriveActivity$7.run(DriveActivity.java:453)
    at java.lang.Thread.run(Thread.java:856)
```

**Comment by giuliohome** [comment]
fix in beta testing

community post: https://plus.google.com/101251753720588443930/posts/Ty9awGPsrx7
